### ISSUE TITLE
MVPリリース(β版)

### ISSUE THREAD

**Issue by kzkio114** [kzkio114/FlowerJewelRing#166]
バグや至らない所多いですが、ご確認お願いいたします。

## 各種情報
サービス名  めぐる宝石花
サービスURL   https://flowerjewelring-e86d8e8259b0.herokuapp.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- [x] ソーシャルログイン機能
~~- [ ] パスワードリセット機能~~
- [x] プロフィール編集機能
- [x] 相談投稿機能
~~- [ ] 相談カテゴリ分け機能~~
- [x] 返信投稿機能
~~- [ ] 1対1チャット機能~~
- [x] チャット暗号化機能
- [x] ギフト送信機能
- [x] ギフト履歴

## READMEレビュー時から変更した機能
- [x] 1対1チャット機能 → 全体チャット機能に変更　MVP後に実装予定
- [x] パスワードリセット機能 → ソーシャルログイン機能だけなので削除
- [x] 相談カテゴリ分け機能 → カテゴリの表示で対応　MVP後に実装予定
### 追加
- [x] トライアルページの作成　観覧可能箇所（相談のタイトル表示・相談返信の累計） 

### タイトル作成
https://github.com/kzkio114/FlowerJewelRing/assets/143789647/62796db7-8916-4674-a7b4-3686aea453a9

### 詳細から相談返信まで
https://github.com/kzkio114/FlowerJewelRing/assets/143789647/b18794d0-308a-465c-a4d2-38f50c98511c

### 通知が来た際の挙動
https://github.com/kzkio114/FlowerJewelRing/assets/143789647/fbc0b9c2-1d9c-4a24-897a-b038a1ad0a4e

### 相談返信に対しての感謝の返信（ギフト）と累計数のカウント
https://github.com/kzkio114/FlowerJewelRing/assets/143789647/f503687e-6853-4a8d-b2e7-c0d95a135d90

### 送られたメッセージの内容
![Image](https://github.com/kzkio114/FlowerJewelRing/assets/143789647/ef674f22-9584-4eb0-b503-7d12ad4e19ff)

### プロフィール詳細・編集機能
https://github.com/kzkio114/FlowerJewelRing/assets/143789647/8649458d-6f33-4d2e-b69b-98e7fd297e6e

### ユーザー詳細
![Image](https://github.com/kzkio114/FlowerJewelRing/assets/143789647/a23ef405-7894-4f05-9ad0-e75ba96a547b)

ご確認、何卒よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by kzkio114** [comment]
> 機能確認が取れました。LGTMです！ 引き続き本リリースに向けて開発頑張ってください。

ありがとうございます！！引き続き頑張ります！！
