### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by kzkio114** [kzkio114/FlowerJewelRing#77]
## 実装予定の機能

- [ ] ソーシャルログイン機能
- [ ] パスワードリセット機能
- [ ] プロフィール編集機能
- [ ] 相談投稿機能
- [ ] 相談カテゴリ分け機能
- [ ] 返信投稿機能
- [ ] 1対1チャット機能
- [ ] チャット暗号化機能
- [ ] チャット履歴機能
- [ ] ギフト送信機能
- [ ] ギフト履歴
- [ ] グループチャット作成機能
- [ ] グループチャットメッセージ機能
- [ ] グループチャットメンバー管理機能
- [ ] 組織管理機能

## 必要なページ

- [ ] トップページ
- [ ] アプリ説明ページ
- [ ] お試しページ
- [ ] ログインページ
- [ ] アバター詳細ページ
- [ ] 花と宝石の累計ページ
- [ ] ユーザーページ
- [ ] 感謝の花と宝石ページ
- [ ] 悩みのカテゴリページ
- [ ] 悩みの返信ページ
- [ ] チャット選択ページ
- [ ] 個人チャットページ
- [ ] グループチャットページ
- [ ] 返信通知ページ
- [ ] 管理ページ
- [ ] 管理者ダッシュボードページ

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。

**Comment by kzkio114** [comment]
> 概ね良いかと思います。LGTMです。

ご確認、ありがとうございます。
